### ISSUE TITLE
Don’t enable logging when used as a library

### ISSUE THREAD

**Issue by robin-nitrokey** [nxp-mcuxpresso/spsdk#54]
Release 1.9.0 adds a logger for the `spsdk` module even if it is only used as a library.  I think this should only be the case for the `spsdk` application or if requested explicitly.

https://github.com/nxp-mcuxpresso/spsdk/blob/cca8819bf19900cd3ead21690501fd5309875e5d/spsdk/__init__.py#L111-L115

**Comment by marekvi95** [comment]
Hello Robin, thanks for reporting this. It will be solved in next release by removing the logger handling from SPSDK init module. Colored logger handler will be added only to CLI applications or if requested explicitly.
