### ISSUE TITLE
Support cryptography 42

### ISSUE THREAD

**Issue by dotlambda** [nxp-mcuxpresso/spsdk#64]
See https://cryptography.io/en/latest/changelog/#v42-0-0 for the changelog.

**Comment by mwsk** [comment]
Hello @dotlambda , cryptography 42 will be supported in next release - 2.1.1

**Comment by dvzrv** [comment]
> Hello @dotlambda , cryptography 42 will be supported in next release - 2.1.1

Hi! :wave: 

I'm currently stuck and can not upgrade python-pynitrokey on Arch Linux due to this issue.
What is the ETA on the next release?

**Comment by mwsk** [comment]
Hello, 2.1.1 is planned for 27 March 2024 :)

**Comment by mwsk** [comment]
Please check the latest release 2.1.1: cryptography>=42.0.0,<42.1

**Comment by mwsk** [comment]
Please check the latest release 2.1.1: cryptography>=42.0.0,<42.1
