### ISSUE TITLE
Use stdlib ast.unparse instead of astunparse

### ISSUE THREAD

**Issue by jjakob** [nxp-mcuxpresso/spsdk#68]
Gentoo is removing astunparse from their repos on 2024-04-09

https://docs.python.org/3/library/ast.html#ast.unparse
https://github.com/simonpercivall/astunparse/issues/67#issuecomment-1438351272

**Comment by mstarecek** [comment]
Hi jjakob. The `ast.unparse` method was added in Python 3.9. But we have to support Python 3.8 as well.
So the best we can do is to limit the usage of `astunparse` to Python 3.8 only.
