### ISSUE TITLE
2.1.1 tests fail with cryptography 42.0.5:  ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.rsa'

### ISSUE THREAD

**Issue by jjakob** [nxp-mcuxpresso/spsdk#69]
#64 should have added support for cryptography >42 <42.1 but tests fail:

```
spsdk/crypto/__init__.py:51: in <module>
    from cryptography.hazmat.backends.openssl.rsa import *
E   ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.rsa'
```

**Comment by mstarecek** [comment]
Hello jjakob, you might be using an older version of SPSDK. (before support for cryptography 42 was added)
In version 2.1.1 the file `spsdk/crypto/__init__.py` doesn't have any content. Please check the version of SPSDK you're using.

**Comment by jjakob** [comment]
You're right, it was a dumb mistake, it was still compiling 1.11.0.
